(()=>{
const files=['meta','pink_tax','style_gender','color_palette','price_ladder','unisex_tone','photo_price','dress_price','roadster_keywords','charm_pricing','color_price_heatmap','capsule'];
Promise.all(files.map(f=>fetch(`data/${f}.json`).then(r=>r.json()))).then(([meta,pt,sg,cp,pl,ut,pp,dp,rk,cp2,hm,cap])=>{
 document.getElementById('meta-note').textContent=`${meta.total_items} items • generated ${meta.date}`;
 renderPinkTax(pt);
 renderStyleGender(sg);
 renderColorPalette(cp);
 renderPriceLadder(pl);
 renderUnisexTone(ut);
 renderPhotoPrice(pp);
 renderDressPrice(dp);
 renderRoadsterKeywords(rk);
 renderCharmPricing(cp2);
 renderColorPriceHeatmap(hm);
 renderCapsule(cap);
});
function svg(sel){return d3.select(sel).append('svg').attr('viewBox','0 0 640 400').attr('preserveAspectRatio','xMidYMid meet');}
function renderPinkTax(d){const s=svg('#chart-pink-tax');const x=d3.scaleBand().domain(d.labels).range([60,600]).padding(0.4);const y=d3.scaleLinear().domain([0,d3.max(d.values)*1.2]).range([350,20]);s.append('g').attr('transform','translate(0,350)').call(d3.axisBottom(x));s.append('g').attr('transform','translate(60,0)').call(d3.axisLeft(y));s.selectAll('rect').data(d.values).enter().append('rect').attr('x',(v,i)=>x(d.labels[i])).attr('y',y(0)).attr('width',x.bandwidth()).attr('height',0).attr('fill','#d5a').transition().duration(400).attr('y',v=>y(v)).attr('height',v=>350-y(v));}
function renderStyleGender(d){const s=svg('#chart-style-gender');const stack=d3.stack().keys(d.styles);const series=stack(d.matrix.map((row,i)=>{let obj={};d.styles.forEach((k,j)=>obj[k]=row[j]);return obj;}));const x=d3.scaleBand().domain(d.genders).range([60,600]).padding(0.2);const y=d3.scaleLinear().domain([0,d3.max(d.matrix.flat())*1.3]).range([350,20]);s.append('g').attr('transform','translate(0,350)').call(d3.axisBottom(x));s.append('g').attr('transform','translate(60,0)').call(d3.axisLeft(y));const color=d3.scaleOrdinal().domain(d.styles).range(d3.schemePastel1);s.selectAll('g.layer').data(series).enter().append('g').attr('fill',d=>color(d.key)).selectAll('rect').data(d=>d).enter().append('rect').attr('x',(d,i)=>x(d.data.index)).attr('y',y(0)).attr('width',x.bandwidth()).attr('height',0).transition().duration(400).attr('y',d=>y(d[1])).attr('height',d=>y(d[0])-y(d[1]));}
function renderColorPalette(d){const s=svg('#chart-color-palette');const x0=d3.scaleBand().domain(d.colors).range([60,600]).padding(0.2);const x1=d3.scaleBand().domain(['Women','Men']).range([0,x0.bandwidth()]).padding(0.05);const y=d3.scaleLinear().domain([0,d3.max([...d.Women,...d.Men])*1.2]).range([350,20]);s.append('g').attr('transform','translate(0,350)').call(d3.axisBottom(x0));s.append('g').attr('transform','translate(60,0)').call(d3.axisLeft(y));const color=d3.scaleOrdinal().domain(['Women','Men']).range(['#e9a','steelblue']);['Women','Men'].forEach(g=>{s.append('g').selectAll('rect.'+g).data(d[g]).enter().append('rect').attr('class',g).attr('x',(v,i)=>x0(d.colors[i])+x1(g)).attr('y',y(0)).attr('width',x1.bandwidth()).attr('height',0).attr('fill',color(g)).transition().duration(400).attr('y',v=>y(v)).attr('height',v=>350-y(v));});}
function renderPriceLadder(d){const s=svg('#chart-price-ladder');const x=d3.scaleBand().domain(d.brands).range([60,600]).padding(0.3);const y=d3.scaleLinear().domain([0,d3.max(d.median)*1.2]).range([350,20]);s.append('g').attr('transform','translate(0,350)').call(d3.axisBottom(x)).selectAll('text').attr('transform','rotate(-45)').style('text-anchor','end');s.append('g').attr('transform','translate(60,0)').call(d3.axisLeft(y));s.selectAll('rect').data(d.median).enter().append('rect').attr('x',(v,i)=>x(d.brands[i])).attr('y',y(0)).attr('width',x.bandwidth()).attr('height',0).attr('fill','#9ad').transition().duration(400).attr('y',v=>y(v)).attr('height',v=>350-y(v));}
function renderUnisexTone(d){const s=svg('#chart-unisex-tone');const x=d3.scaleBand().domain(d.labels).range([60,600]).padding(0.4);const y=d3.scaleLinear().domain([0,d3.max(d.counts)*1.2]).range([350,20]);s.append('g').attr('transform','translate(0,350)').call(d3.axisBottom(x));s.append('g').attr('transform','translate(60,0)').call(d3.axisLeft(y));s.selectAll('rect').data(d.counts).enter().append('rect').attr('x',(v,i)=>x(d.labels[i])).attr('y',y(0)).attr('width',x.bandwidth()).attr('height',0).attr('fill','#fc8').transition().duration(400).attr('y',v=>y(v)).attr('height',v=>350-y(v));}
function renderPhotoPrice(d){const s=svg('#chart-photo-price');const x=d3.scaleLinear().domain([0,d3.max(d.points,pt=>pt[1])]).range([60,600]);const y=d3.scaleLinear().domain([0,d3.max(d.points,pt=>pt[0])]).range([350,20]);s.append('g').attr('transform','translate(0,350)').call(d3.axisBottom(x));s.append('g').attr('transform','translate(60,0)').call(d3.axisLeft(y));s.append('line').attr('x1',x(0)).attr('x2',x(d3.max(d.points,pt=>pt[1]))).attr('y1',y(d.intercept)).attr('y2',y(d.slope*d3.max(d.points,pt=>pt[1])+d.intercept)).attr('stroke','#888');s.append('g').selectAll('circle').data(d.points).enter().append('circle').attr('cx',pt=>x(pt[1])).attr('cy',y(0)).attr('r',3).attr('fill','steelblue').transition().duration(400).attr('cy',pt=>y(pt[0]));}
function renderDressPrice(d){const s=svg('#chart-dress-price');const x=d3.scaleBand().domain(d.codes).range([60,600]).padding(0.4);const y=d3.scaleLinear().domain([0,d3.max(d.stats.flat())*1.1]).range([350,20]);s.append('g').attr('transform','translate(0,350)').call(d3.axisBottom(x));s.append('g').attr('transform','translate(60,0)').call(d3.axisLeft(y));const box=s.selectAll('g.box').data(d.stats).enter().append('g').attr('transform',(v,i)=>`translate(${x(d.codes[i])},0)`);box.append('line').attr('y1',v=>y(v[0])).attr('y2',v=>y(v[4])).attr('x1',x.bandwidth()/2).attr('x2',x.bandwidth()/2).attr('stroke','#555');box.append('rect').attr('y',v=>y(v[3])).attr('height',v=>y(v[1])-y(v[3])).attr('width',x.bandwidth()).attr('fill','#cde');box.append('line').attr('y1',v=>y(v[2])).attr('y2',v=>y(v[2])).attr('x1',0).attr('x2',x.bandwidth()).attr('stroke','#333');}
function renderRoadsterKeywords(d){const s=svg('#chart-roadster-keywords');const x=d3.scaleLinear().domain([0,d3.max(d.counts)]).range([150,600]);const y=d3.scaleBand().domain(d.words).range([20,380]).padding(0.1);s.append('g').attr('transform','translate(150,0)').call(d3.axisLeft(y));s.append('g').attr('transform','translate(0,380)').call(d3.axisBottom(x));s.selectAll('rect').data(d.counts).enter().append('rect').attr('y',(v,i)=>y(d.words[i])).attr('x',150).attr('height',y.bandwidth()).attr('width',0).attr('fill','#9bc').transition().duration(400).attr('width',v=>x(v)-150);}
function renderCharmPricing(d){const s=svg('#chart-charm-pricing');const x=d3.scaleBand().domain(d.labels).range([60,600]).padding(0.4);const y=d3.scaleLinear().domain([0,d3.max(d.counts)*1.2]).range([350,20]);s.append('g').attr('transform','translate(0,350)').call(d3.axisBottom(x));s.append('g').attr('transform','translate(60,0)').call(d3.axisLeft(y));s.selectAll('rect').data(d.counts).enter().append('rect').attr('x',(v,i)=>x(d.labels[i])).attr('y',y(0)).attr('width',x.bandwidth()).attr('height',0).attr('fill','#fad').transition().duration(400).attr('y',v=>y(v)).attr('height',v=>350-y(v));}
function renderColorPriceHeatmap(d){const s=svg('#chart-color-price-heatmap');const x=d3.scaleBand().domain(d.colors).range([60,600]).padding(0.05);const y=d3.scaleBand().domain(d.buckets).range([20,350]).padding(0.05);const color=d3.scaleSequential(d3.interpolateBlues).domain([0,d3.max(d.matrix.flat())]);s.append('g').attr('transform','translate(0,350)').call(d3.axisBottom(x));s.append('g').attr('transform','translate(60,0)').call(d3.axisLeft(y));const g=s.append('g');d.colors.forEach((c,i)=>{d.buckets.forEach((b,j)=>{g.append('rect').attr('x',x(c)).attr('y',y(b)).attr('width',x.bandwidth()).attr('height',y.bandwidth()).attr('fill',color(0)).transition().duration(400).attr('fill',color(d.matrix[i][j]));});});}
function renderCapsule(d){const div=d3.select('#chart-capsule');div.html('');const table=div.append('table');const thead=table.append('thead').append('tr');['Brand','Item','Price','Color','Gender'].forEach(h=>thead.append('th').text(h));const tbody=table.append('tbody');d.items.forEach(r=>{const tr=tbody.append('tr');tr.append('td').text(r.brand);tr.append('td').text(r.name);tr.append('td').text(`₹${r.price}`);tr.append('td').text(r.color);tr.append('td').text(r.gender);});}
})();
